### ISSUE TITLE
Use Package Structure for Easy Importing

### ISSUE THREAD

**Issue by dcarroll** [enreeco/lightning-progressbar#2]
@enreeco - If you add a package.xml and rename the src folder to a more specific name like "ProgressBar" then this code can be imported in a single go using the Force CLI.

`force push -t Package -n ProgressBar`

http://force-cli.herokuapp.com/

**Comment by enreeco** [comment]
Totally agree

**Comment by enreeco** [comment]
Package structure refactored from pull request
